version: '3.8'

services:
  todo:
    image: todo:latest
    ports:
      - '8080:8080'
    environment:
      APP_ENV: DEV
      REDIS_CACHE_ENTITY_EXPIRATION_HOURS: 1

      SQL_SERVER: postgres
      SQL_USER: postgres
      SQL_PASSWORD: postgres
      SQL_DATABASE: todo
      X_API_HEADER: 9f3c5a8d3b6e4f1ab2d3e7c9a1f0b3d4c5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0
      REDIS_SERVER: redis
      REDIS_USER: dotnet-sign
      REDIS_PASSWORD: xxx
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:7
    ports:
      - '6379:6379'

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-init:
    image: postgres:15
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  postgres_data:
